console.log(NaN == NaN);
console.log(+0 == -0);
console.log("sanket" === 'sanket')
console.log(null === null)
console.log({} == {})
console.log(undefined == null);
console.log(null == undefined);
console.log(10 == '10')
console.log(10 == '12');